### ISSUE TITLE
[Source Request] ManaToki/NewToki

### ISSUE THREAD

**Issue by nar1n** [Paperback-iOS/extensions-foreign#25]
- [x] https://manatoki95.net/
- [x] https://newtoki95.com/

**Comment by nar1n** [comment]
ManaToki added

**Comment by HaeyoungKwon** [comment]
please, add NewToki and fix ManaToki
(with Paperback 0.6 compatibility)

**Comment by nouun** [comment]
cc/ @HaeyoungKwon 

뉴토끼 has been added to my foreign extension list. 
https://nouun.github.io/paperback-extensions/foreign

If someone better at Korean could check grammar/spelling of the settings and home tiles it would be appreciated as my Korean is rather mediocre.
