### ISSUE TITLE
[Sources Request] Add French sources

### ISSUE THREAD

**Issue by ClarkyK3nt** [Paperback-iOS/extensions-foreign#40]
Hello, I don’t see any french sources anymore:
https://www.japscan.se/
https://scantrad.net/
https://lelscan-vf.co/

**Comment by TheNetsky** [comment]
Actually as a follow up now that this issue has been transfered, all these sites have already been requested.
Check #29

**Comment by ClarkyK3nt** [comment]
> Actually as a follow up now that this issue has been transferred, all these sites have already been requested.
> Check #29

I didn’t see it. Thanks for all the work you do for the community!

**Comment by AdrienSeon** [comment]
Thanks for the request! 
Unfortunately, this source has already been asked before in #29 

We will then close this one since it is a duplicate.
