### ISSUE TITLE
[Bug] Fix BainianManga title and image source

### ISSUE THREAD

**Issue by ggl-wolfy** [Paperback-iOS/extensions-foreign#48]
Please fix the title in the details screen by removing the string "漫画免费阅读全集-百年漫画" after the name.

![IMG_0342](https://user-images.githubusercontent.com/58021228/125228956-18852a80-e319-11eb-996e-81ef765ea4b2.jpeg)

The title as shown in "details":
![IMG_0343](https://user-images.githubusercontent.com/58021228/125228995-2c309100-e319-11eb-8235-c3c3872ed21a.jpeg)

Another issue, images recently are not showing. A black screen with an error message appears mentioning an invalid certificate from "img.lxhy88.com". I suppose this is because they changed the image domain to "img.glyf168.com"?

Thanks.

**Comment by getBoolean** [comment]
Sorry for the delay, was busy with a summer class. I've opened the PR and it should be merged within a few days

**Comment by ggl-wolfy** [comment]
Thanks!
