### ISSUE TITLE
Add japscan (french)

### ISSUE THREAD

**Issue by az4521** [Paperback-iOS/extensions-foreign#6]
japscan is the best french source for manga. I have no ulterior motives in requesting it.

https://www.japscan.se/

**Comment by AdrienSeon** [comment]
I see you https://github.com/tachiyomiorg/tachiyomi-extensions/pull/4772 😛 
You just want to see us sweat too 😢 

For now we will unfortunately have to postpone implementing this source see https://github.com/Paperback-iOS/extensions-promises/issues/142

GL on your side to maintain it

**Comment by az4521** [comment]
damn shawty, ok.
